name = "RingMatrices"
uuid = "51b861e0-f9cd-4150-986a-4c315c34a2af"
authors = ["Roger Herikstad <roger.herikstad@gmail.com>"]
version = "0.4.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
